version: "2"
run:
  concurrency: 10
linters:
  enable:
    - asasalint
    - bodyclose
    - containedctx
    - contextcheck
    - cyclop
    - decorder
    - dupl
    - dupword
    - durationcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - forcetypeassert
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - godot
    - godox
    - goprintffuncname
    - gosmopolitan
    - misspell
    - paralleltest
    - prealloc
    - predeclared
    - reassign
    - revive
    - tparallel
    - unparam
    - wrapcheck
    - wsl
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
